//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackList
    {
        public int idPenalizacion { get; set; }
        public int idUsuario { get; set; }
        public string justificacion { get; set; }
        public Nullable<System.DateTime> fechaPenalizacion { get; set; }
        public Nullable<System.DateTime> fechaDespenalizacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
