//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public Direccion()
        {
            this.DatosPersonales = new HashSet<DatosPersonales>();
            this.Sucursal = new HashSet<Sucursal>();
        }
    
        public int idDireccion { get; set; }
        public string direccion1 { get; set; }
        public string codigoPostal { get; set; }
    
        public virtual ICollection<DatosPersonales> DatosPersonales { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
    }
}
