//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecommerceEntities : DbContext
    {
        public ecommerceEntities()
            : base("name=ecommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BlackList> BlackList { get; set; }
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<Color> Color { get; set; }
        public DbSet<Cupon> Cupon { get; set; }
        public DbSet<DatosPersonales> DatosPersonales { get; set; }
        public DbSet<Direccion> Direccion { get; set; }
        public DbSet<Envio> Envio { get; set; }
        public DbSet<EstadoPago> EstadoPago { get; set; }
        public DbSet<Factura> Factura { get; set; }
        public DbSet<Garantia> Garantia { get; set; }
        public DbSet<OrdenCompra> OrdenCompra { get; set; }
        public DbSet<OrdenCompraDetalle> OrdenCompraDetalle { get; set; }
        public DbSet<OrdenCompraEnvio> OrdenCompraEnvio { get; set; }
        public DbSet<OrdenCompraEstado> OrdenCompraEstado { get; set; }
        public DbSet<Pago> Pago { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Stock> Stock { get; set; }
        public DbSet<Sucursal> Sucursal { get; set; }
        public DbSet<Talle> Talle { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<UsuarioEstado> UsuarioEstado { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
