//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenProducto
    {
        public Nullable<int> idProducto { get; set; }
        public decimal peso { get; set; }
        public string url { get; set; }
        public string extension { get; set; }
        public Nullable<bool> esCarrusel { get; set; }
        public int id { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
