//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenCompra()
        {
            this.OrdenCompraDetalle = new HashSet<OrdenCompraDetalle>();
            this.OrdenCompraEnvio = new HashSet<OrdenCompraEnvio>();
        }
    
        public int idOrdenCompra { get; set; }
        public int idUsuario { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public Nullable<int> idCupon { get; set; }
        public Nullable<int> idOrdenCompraEnvio { get; set; }
        public Nullable<int> idPago { get; set; }
        public int idEstadoOrden { get; set; }
        public Nullable<System.DateTime> fechaCompra { get; set; }
    
        public virtual Cupon Cupon { get; set; }
        public virtual OrdenCompraEstado OrdenCompraEstado { get; set; }
        public virtual Pago Pago { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraDetalle> OrdenCompraDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraEnvio> OrdenCompraEnvio { get; set; }
    }
}
