//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public Pago()
        {
            this.Factura = new HashSet<Factura>();
            this.OrdenCompra = new HashSet<OrdenCompra>();
        }
    
        public int idPago { get; set; }
        public int tipoPago { get; set; }
        public decimal total { get; set; }
        public int idEstadoPago { get; set; }
    
        public virtual EstadoPago EstadoPago { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<OrdenCompra> OrdenCompra { get; set; }
    }
}
