//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        public Producto()
        {
            this.OrdenCompraDetalle = new HashSet<OrdenCompraDetalle>();
            this.Stock = new HashSet<Stock>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int idProducto { get; set; }

        [Display(Name = "Categoría")]
        public int idCategoria { get; set; }

        [Display(Name = "Descripción del producto")]
        public string descripcion { get; set; }

        [Display(Name = "Talle")]
        public Nullable<int> idTalle { get; set; }

        [Display(Name = "Precio unitario")]
        public decimal precioUnitario { get; set; }

        [Display(Name = "Duración de garantía")]
        public int idGarantia { get; set; }

        [Display(Name = "Color")]
        public int idColor { get; set; }

        [Display(Name = "Imagen principal del producto")]
        public string fotoUrl { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Color Color { get; set; }
        public virtual Garantia Garantia { get; set; }
        public virtual ICollection<OrdenCompraDetalle> OrdenCompraDetalle { get; set; }
        public virtual Talle Talle { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
