//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.OrdenCompraDetalle = new HashSet<OrdenCompraDetalle>();
            this.Stock = new HashSet<Stock>();
            this.WishList = new HashSet<WishList>();
        }
    
        public int idProducto { get; set; }
        public int idCategoria { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idTalle { get; set; }
        public decimal precioUnitario { get; set; }
        public Nullable<int> idGarantia { get; set; }
        public int idColor { get; set; }
        public string fotoUrl { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Color Color { get; set; }
        public virtual Garantia Garantia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraDetalle> OrdenCompraDetalle { get; set; }
        public virtual Talle Talle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishList { get; set; }
    }
}
