//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public Sucursal()
        {
            this.OrdenCompra = new HashSet<OrdenCompra>();
            this.Stock = new HashSet<Stock>();
        }
    
        public int idSucursal { get; set; }
        public int idDireccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string descripcion { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual ICollection<OrdenCompra> OrdenCompra { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
