//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF_Base.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talle
    {
        public Talle()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int idTalle { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
